CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_number VARCHAR(32) NOT NULL UNIQUE,
    customer_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE webauthn_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    credential_id VARCHAR(512) NOT NULL UNIQUE,
    public_key VARCHAR(2048) NOT NULL,
    sign_count BIGINT NOT NULL,
    backup_eligible BOOLEAN NOT NULL,
    backup_state BOOLEAN NOT NULL,
    transports VARCHAR(512),
    created_at TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_webauthn_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE payment_intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    txn_id VARCHAR(64) NOT NULL UNIQUE,
    payee_vpa VARCHAR(128) NOT NULL,
    payee_name VARCHAR(128) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency VARCHAR(8) NOT NULL,
    purpose VARCHAR(256) NOT NULL,
    nonce VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE payment_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_id BIGINT NOT NULL,
    challenge_b64url VARCHAR(256) NOT NULL,
    txn_hash_hex VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_intent FOREIGN KEY (intent_id) REFERENCES payment_intents(id)
);
